version: 2.1

jobs:
  build:
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:3.1-buster  
  
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run: docker-compose build
