version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
  
    steps:
      - checkout
      - run:
          name: Build Server Image
          command: |
            docker build -t rumitparakhiya/thewatchman-server:latest -f TheWatchman.Server/Dockerfile .
      - run:
          name: Publish Server Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push rumitparakhiya/thewatchman-server:latest

      - run:
          name: Build Monitor Image
          command: |
            docker build -t rumitparakhiya/thewatchman-monitor:latest -f TheWatchman.Monitor/Dockerfile .
      - run:
          name: Publish Monitor Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push rumitparakhiya/thewatchman-monitor:latest
